version = 1

exclude_patterns = [
    ".pnp.js",
    ".yarn/**/*",
    ".vscode/**/*",
    "**/test/snapshots"
]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  module_system = "commonjs"
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true
